"""
Simulierte Ziegler Produktdatenbank.
Echte Daten kommen später aus SAP/Excel.
"""

VEHICLES = [
    {
        "id": "hlf20_z",
        "name": "HLF 20 / Z-Klasse",
        "type": "HLF 20",
        "description": "Hilfeleistungslöschgruppenfahrzeug — Flaggschiff",
        "specs": {
            "motor_kw": 295,
            "torque_nm": 1400,
            "pump_type": "FPN 10-3000",
            "pump_lpm": 3000,
            "tank_liters": 2000,
            "drive": "Allradantrieb 4×4",
            "height_m": 3.30,
            "weight_kg": 16000,
            "speed_kmh": 120,
            "guarantee_months": 24,
            "spare_parts_years": 20,
            "service_hours": 48,
            "norms": [
                "DIN 14530-27",
                "DIN EN 1846-1",
                "DIN EN 1846-2",
                "DIN EN 1028-1",
                "ISO 9001:2015",
                "UVgO",
                "VOL/A",
            ],
        },
    },
    {
        "id": "hlf10_z",
        "name": "HLF 10 / Z-Klasse",
        "type": "HLF 10",
        "description": "Hilfeleistungslöschgruppenfahrzeug kompakt",
        "specs": {
            "motor_kw": 220,
            "torque_nm": 1050,
            "pump_type": "FPN 10-2000",
            "pump_lpm": 2000,
            "tank_liters": 1000,
            "drive": "Allradantrieb 4×4",
            "height_m": 3.20,
            "weight_kg": 14000,
            "speed_kmh": 120,
            "guarantee_months": 24,
            "spare_parts_years": 20,
            "service_hours": 48,
            "norms": [
                "DIN 14530-26",
                "DIN EN 1846-1",
                "DIN EN 1846-2",
                "DIN EN 1028-1",
                "ISO 9001:2015",
            ],
        },
    },
    {
        "id": "lf20_kats",
        "name": "LF 20 KatS",
        "type": "LF 20",
        "description": "Löschgruppenfahrzeug Katastrophenschutz",
        "specs": {
            "motor_kw": 220,
            "torque_nm": 1050,
            "pump_type": "FPN 10-2000",
            "pump_lpm": 2000,
            "tank_liters": 1600,
            "drive": "Allradantrieb 4×4",
            "height_m": 3.20,
            "weight_kg": 14500,
            "speed_kmh": 120,
            "guarantee_months": 24,
            "spare_parts_years": 15,
            "service_hours": 48,
            "norms": [
                "DIN 14530-5",
                "DIN EN 1846-2",
                "DIN EN 1028-1",
                "ISO 9001:2015",
                "VOB/A",
            ],
        },
    },
    {
        "id": "tlf4000",
        "name": "TLF 4000",
        "type": "TLF 4000",
        "description": "Tanklöschfahrzeug — großes Wasservolumen",
        "specs": {
            "motor_kw": 260,
            "torque_nm": 1250,
            "pump_type": "FPN 10-3000",
            "pump_lpm": 3000,
            "tank_liters": 4000,
            "drive": "Allradantrieb 4×4",
            "height_m": 3.50,
            "weight_kg": 18000,
            "speed_kmh": 110,
            "guarantee_months": 24,
            "spare_parts_years": 20,
            "service_hours": 48,
            "norms": [
                "DIN 14530-22",
                "DIN EN 1846-2",
                "DIN EN 1028-1",
                "ISO 9001:2015",
            ],
        },
    },
    {
        "id": "mlf_dokab",
        "name": "MLF DoKa",
        "type": "MLF",
        "description": "Mittleres Löschfahrzeug — Doppelkabine",
        "specs": {
            "motor_kw": 130,
            "torque_nm": 500,
            "pump_type": "FPN 10-1000",
            "pump_lpm": 1000,
            "tank_liters": 750,
            "drive": "Hinterradantrieb 4×2",
            "height_m": 2.95,
            "weight_kg": 7500,
            "speed_kmh": 120,
            "guarantee_months": 24,
            "spare_parts_years": 15,
            "service_hours": 72,
            "norms": [
                "DIN 14530-25",
                "DIN EN 1846-2",
                "DIN EN 1028-1",
                "ISO 9001:2015",
            ],
        },
    },
    {
        "id": "tsfw",
        "name": "TSF-W",
        "type": "TSF-W",
        "description": "Tragkraftspritzenfahrzeug-Wasser — Kleinstgemeinden",
        "specs": {
            "motor_kw": 110,
            "torque_nm": 390,
            "pump_type": "PFPN 10-1000",
            "pump_lpm": 1000,
            "tank_liters": 500,
            "drive": "Hinterradantrieb 4×2",
            "height_m": 2.85,
            "weight_kg": 5000,
            "speed_kmh": 120,
            "guarantee_months": 24,
            "spare_parts_years": 10,
            "service_hours": 72,
            "norms": [
                "DIN 14530-16",
                "DIN EN 1846-2",
                "ISO 9001:2015",
            ],
        },
    },
]
